services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URI=http://auth-service:8081

    networks:
      - internal

networks:
  internal:
    external: true