spring:
  application:
    name: Auth Service

server:
  port: 8081

custom:
  errors:
    user-not-found-status-code: 404
    user-not-found-message: ERROR_USER_NOT_FOUND

    unauthorized-status-code: 401
    unauthorized-message: ERROR_UNAUTHORIZED

    validation-failed-status-code: 400
    validation-failed-message: ERROR_VALIDATION_FAILED

    app-error-status-code: 400
    app-error-message: ERROR_APPLICATION