server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/auth/**

        - id: auth-service-user-route
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/user/**
          filters:
            - name: JwtValidation
              args:
                roles: USER

        - id: auth-service-admin-route
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/admin/**
          filters:
            - name: JwtValidation
              args:
                roles: ADMIN