services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - internal

networks:
  internal:
    external: true