spring:
  application:
    name: Cart Service

server:
  port: 8082


custom:
  errors:
    unauthorized:
      statusCode: 401
      message: You are not authorized to perform this action.
    notFound:
      statusCode: 404
      message: Resource not found.
    validationFailed:
      statusCode: 400
      message: Validation failed.
    appError:
      statusCode: 500
      message: An unexpected error occurred.